
export const COMPARISON_CARDS = [
  {
    id: "cmp-resp-photo",
    unit: 4,
    ref: "4.2/LO3 · 4.3/LO5",
    title: "Respiration vs Photosynthesis",
    subtitle: "Two opposite processes that pass energy through living things.",
    a: {
      name: "Photosynthesis",
      accent: "teal",
      kicker: "Makes glucose using light energy",
      visualKey: "chloroplast",
      equation: ["carbon dioxide", "+", "water", "→", "glucose", "+", "oxygen"],
      energyStory: ["LIGHT ENERGY", "CHEMICAL ENERGY IN GLUCOSE"],
    },
    b: {
      name: "Respiration",
      accent: "coral",
      kicker: "Releases usable energy from food",
      visualKey: "mitochondrion",
      equation: ["glucose", "+", "oxygen", "→", "carbon dioxide", "+", "water"],
      energyStory: ["CHEMICAL ENERGY IN GLUCOSE", "USABLE ENERGY FOR CELLS"],
    },
    rows: [
      { label: "Purpose", a: "Makes organic food (glucose).", b: "Releases energy the cell can use." },
      { label: "Main site", a: "Chloroplasts.", b: "Mitochondria." },
      { label: "Needs light?", a: "Yes — light provides the energy.", b: "No — continues day and night." },
      { label: "Gases", a: "Uses carbon dioxide, releases oxygen.", b: "Uses oxygen, releases carbon dioxide." },
      { label: "Who does it?", a: "Photosynthetic organisms only.", b: "All living organisms." },
    ],
    memoryHook: "Photosynthesis stores light energy in glucose; respiration releases that stored energy for cells to use.",
    quickTest: {
      q: "Which process releases usable energy from glucose?",
      options: ["Photosynthesis", "Respiration"],
      answer: 1,
      feedback: "Photosynthesis makes glucose; respiration releases the energy from it.",
    },
  },
  {
    id: "cmp-seagrass-kelp",
    unit: 3,
    ref: "3.5/LO1–2 · 3.3/LO4",
    title: "Seagrass vs Kelp",
    subtitle: "They look like underwater plants, but only one is a true plant.",
    a: { name: "Seagrass", accent: "teal", kicker: "A true flowering plant", visualKey: "seagrass" },
    b: { name: "Kelp", accent: "coral", kicker: "A large protoctist (macroalga)", visualKey: "kelp" },
    rows: [
      { label: "Kingdom", a: "Plant.", b: "Protoctist." },
      { label: "Anchoring", a: "True roots — anchor AND take up minerals.", b: "Holdfast — grips the rock only, takes up nothing." },
      { label: "Structure", a: "Roots, stem and leaves.", b: "Holdfast, stipe and blades (not true roots/stems/leaves)." },
      { label: "Reproduction", a: "Has flowers → sexual reproduction (rhizome spreads it asexually).", b: "No flowers." },
      { label: "Staying up", a: "Rooted in the sediment.", b: "Gas bladders float the blades up toward the light." },
    ],
    memoryHook: "Seagrass is a true plant — roots and flowers; kelp is a protoctist that only holds fast to rock and has no flowers.",
    quickTest: {
      q: "Which one is a protoctist, not a true plant?",
      options: ["Seagrass", "Kelp"],
      answer: 1,
      feedback: "Kelp has a holdfast (not true roots) and no flowers, so it is a protoctist macroalga.",
    },
  },
  {
    id: "cmp-dino-diatom",
    unit: 3,
    ref: "3.5/LO3–4",
    title: "Dinoflagellate vs Diatom",
    subtitle: "Two microscopic photosynthetic protoctists of the plankton.",
    a: { name: "Dinoflagellate", accent: "teal", kicker: "Swims with flagella", visualKey: "dinoflagellate" },
    b: { name: "Diatom", accent: "coral", kicker: "Has a silica skeleton", visualKey: "diatom" },
    rows: [
      { label: "Kingdom", a: "Protoctist.", b: "Protoctist.", shared: true },
      { label: "Nutrition", a: "Photosynthetic — has chloroplasts.", b: "Photosynthetic — has chloroplasts.", shared: true },
      { label: "Size", a: "Microscopic, single-celled.", b: "Microscopic, single-celled.", shared: true },
      { label: "Movement", a: "Two flagella — can move itself.", b: "No flagella — drifts with the water." },
      { label: "Skeleton", a: "No silica skeleton.", b: "Rigid skeleton (frustule) made of silica." },
    ],
    memoryHook: "Both are microscopic photosynthetic protoctists — tell them apart by the flagella (dinoflagellate) and the silica skeleton (diatom).",
    quickTest: {
      q: "Which one has a skeleton made of silica?",
      options: ["Dinoflagellate", "Diatom"],
      answer: 1,
      feedback: "Diatoms have a rigid silica skeleton (frustule); dinoflagellates have two flagella instead.",
    },
  },
  {
    id: "cmp-sonar-radar",
    unit: 6,
    ref: "6.3/LO3",
    title: "Sonar vs Radar",
    subtitle: "Both send a pulse and time the echo — but through different media.",
    a: { name: "Sonar", accent: "teal", kicker: "Sound, through water", visualKey: "sonar" },
    b: { name: "Radar", accent: "coral", kicker: "Radio waves, through air", visualKey: "radar" },
    rows: [
      { label: "How it works", a: "Sends a pulse and times the reflection that bounces back.", b: "Sends a pulse and times the reflection that bounces back.", shared: true },
      { label: "Wave used", a: "Sound (ultrasound) waves.", b: "Radio waves." },
      { label: "Travels through", a: "Water.", b: "Air." },
      { label: "Aimed", a: "Down into the sea.", b: "Out across the surface and air." },
      { label: "Detects", a: "Depth to the seabed and shoals of fish.", b: "Other ships, coastlines and obstacles." },
    ],
    memoryHook: "Both time an echo. Sonar = SOund through water, down to fish and seabed; radar = radio waves through air, out to ships and coast.",
    quickTest: {
      q: "Which is used to find shoals of fish and measure the depth to the seabed?",
      options: ["Sonar", "Radar"],
      answer: 0,
      feedback: "Sonar sends sound down through the water; radar uses radio waves through the air to find ships and coastlines.",
    },
  },
  {
    id: "cmp-sandy-muddy",
    unit: 5,
    ref: "5.5/LO2",
    title: "Sandy shore vs Muddy shore",
    subtitle: "The oxygen difference is the opposite of what most people expect.",
    a: { name: "Sandy shore", accent: "teal", kicker: "Coarse grains, well drained", visualKey: "sand" },
    b: { name: "Muddy shore", accent: "coral", kicker: "Fine particles, waterlogged", visualKey: "mud" },
    rows: [
      { label: "Particle size", a: "Large, coarse grains.", b: "Very fine particles." },
      { label: "Air spaces", a: "Big spaces between grains — hold air.", b: "Tiny spaces — waterlogged, little air." },
      { label: "Oxygen", a: "MORE oxygen in the sediment.", b: "Very little oxygen below the surface." },
      { label: "Stability", a: "Shifts with the waves — unstable.", b: "More stable, but low in oxygen." },
      { label: "Living there", a: "Burrowers cope with shifting sand.", b: "Burrowers need low-oxygen adaptations (e.g. lugworm haemoglobin)." },
    ],
    memoryHook: "Big sand grains leave large air spaces, so a sandy shore holds MORE oxygen than fine, waterlogged mud — not less.",
    quickTest: {
      q: "Which sediment contains more oxygen?",
      options: ["Sandy shore", "Muddy shore"],
      answer: 0,
      feedback: "Large sand grains leave big air spaces, so sand is better oxygenated than fine, waterlogged mud.",
    },
  },
  {
    id: "cmp-fossil-renewable",
    unit: 6,
    ref: "6.5/LO7–8",
    title: "Fossil fuels vs Ocean renewables",
    subtitle: "Reliable-but-finite against clean-but-variable.",
    a: { name: "Fossil fuels", accent: "coral", kicker: "Coal, oil and gas — finite", visualKey: "fossil" },
    b: { name: "Ocean renewables", accent: "teal", kicker: "Tides, waves and wind — not used up", visualKey: "renewable" },
    rows: [
      { label: "Supply", a: "Finite — will run out (non-renewable).", b: "Effectively unlimited (renewable)." },
      { label: "Reliability", a: "Constant supply, unaffected by weather.", b: "Varies with the tide, wind or waves." },
      { label: "Climate", a: "Burning releases CO₂ → enhanced greenhouse effect.", b: "No CO₂ released while generating." },
      { label: "Main harm", a: "Air pollution, oil spills, climate change.", b: "Costly to build; can harm wildlife (turbines) and the seabed (cables/barrages)." },
      { label: "Cost pattern", a: "Cheaper to build, but ongoing fuel cost and pollution.", b: "Expensive to build, but clean and cheap to run." },
    ],
    memoryHook: "Fossil fuels are reliable but finite and release CO₂; ocean renewables are clean and unlimited but weather-dependent and costly to build.",
    quickTest: {
      q: "Which energy source releases carbon dioxide that adds to the greenhouse effect?",
      options: ["Fossil fuels", "Ocean renewables"],
      answer: 0,
      feedback: "Burning fossil fuels releases CO₂; tidal, wave and wind energy release none while generating.",
    },
  },
  {
    id: "cmp-open-closed-aquaculture",
    unit: 6,
    ref: "6.4/LO4",
    title: "Open vs Closed aquaculture",
    subtitle: "Whether the farm exchanges water — and problems — with the open sea.",
    a: { name: "Open system", accent: "teal", kicker: "Cages or nets in the open sea", visualKey: "openAquaculture" },
    b: { name: "Closed system", accent: "coral", kicker: "Sealed tanks on land", visualKey: "closedAquaculture" },
    rows: [
      { label: "Water", a: "Flows freely between the cage and the sea.", b: "Contained, pumped and filtered." },
      { label: "Waste", a: "Food and faeces escape into the sea.", b: "Collected and treated." },
      { label: "Disease", a: "Parasites and disease pass to/from wild fish.", b: "Isolated from wild populations." },
      { label: "Escapes", a: "Farmed fish can escape and interbreed or compete with wild fish.", b: "Escapes very unlikely." },
      { label: "Cost", a: "Cheaper — uses natural conditions.", b: "Expensive to build and run (pumps, filters)." },
    ],
    memoryHook: "Open systems sit in the sea and exchange water — and waste, disease and escapes — with it; closed systems are sealed tanks that isolate the fish but cost more.",
    quickTest: {
      q: "In which system can waste and parasites pass freely to wild fish?",
      options: ["Open system", "Closed system"],
      answer: 0,
      feedback: "An open cage exchanges water with the sea, so waste, parasites and escapes reach wild populations; a closed tank isolates them.",
    },
  },
];

export function getComparisonCard(id) {
  return COMPARISON_CARDS.find((card) => card.id === id);
}
