// Marine Science IGCSE 0697 — True/False bank (Units 1–6)
// Authored from the unit Curriculum Knowledge Models via the exam-question-authoring method.
// Each item is a misconception test; verdicts are balanced ~4 true / 4 false per unit so the
// answer can't be pattern-guessed. Tier 1 = recall, Tier 2 = application.
// App runtime shape: { id, topic, type:"truefalse", stem, answer(bool), why }.
// Extra fields (unit, spec, tier, misconception) are bank metadata for vetting/splicing.
// STATUS: human_review — vet (Don/Kiran) before going live.

export const TRUEFALSE = [
  // ============================ UNIT 1 — The Earth and its oceans ============================
  { id:"TF-U1-01", unit:1, topic:"1.2 Plate tectonics", spec:"1.2/LO6", tier:1, type:"truefalse",
    stem:"A tsunami is a very large wave caused by strong winds.",
    answer:false,
    why:"A tsunami forms when a sudden movement of the seabed (e.g. an earthquake at a plate boundary) displaces a large volume of water; it grows in height in shallow water.",
    misconception:"tsunami = a giant wind wave" },
  { id:"TF-U1-02", unit:1, topic:"1.4 Tides & currents", spec:"1.4/LO1", tier:1, type:"truefalse",
    stem:"Spring tides only happen during the spring season.",
    answer:false,
    why:"Spring tides occur whenever the Sun and Moon are in line, so their gravitational pulls combine to give a larger tidal range — unrelated to the season.",
    misconception:"'spring tide' means springtime" },
  { id:"TF-U1-03", unit:1, topic:"1.3 Oceans & sea floor", spec:"1.3/LO4", tier:1, type:"truefalse",
    stem:"The oceans cover about 71% of the Earth's surface.",
    answer:true,
    why:"Syllabus fact: the oceans cover 71% of the surface and hold 97% of the Earth's water.",
    misconception:"71% and 97% swapped, or 'about half'" },
  { id:"TF-U1-04", unit:1, topic:"1.4 Tides & currents", spec:"1.4/LO4", tier:1, type:"truefalse",
    stem:"Ocean currents are caused only by the tides.",
    answer:false,
    why:"Currents are caused by prevailing winds, the spinning of the Earth, tides and changes in water density — four causes, not one.",
    misconception:"tides are the sole cause of currents" },
  { id:"TF-U1-05", unit:1, topic:"1.1 Earth structure", spec:"1.1/LO3", tier:1, type:"truefalse",
    stem:"The Earth's outer core is liquid.",
    answer:true,
    why:"The iron core has a solid inner core and a liquid outer core; the mantle and crust are solid rock.",
    misconception:"the whole core is solid, or the whole core is liquid" },
  { id:"TF-U1-06", unit:1, topic:"1.2 Plate tectonics", spec:"1.2/LO4", tier:1, type:"truefalse",
    stem:"At a divergent (constructive) boundary the plates move apart.",
    answer:true,
    why:"Divergent = plates move apart; convergent = towards each other; transform = slide past.",
    misconception:"divergent means plates collide" },
  { id:"TF-U1-07", unit:1, topic:"1.3 Oceans & sea floor", spec:"1.3/LO6", tier:2, type:"truefalse",
    stem:"The continental shelf is the deep, flat floor of the open ocean.",
    answer:false,
    why:"The continental shelf is the shallow, gently sloping platform next to the coast; the deep flat floor is the abyssal plain.",
    misconception:"shelf and abyssal plain confused" },
  { id:"TF-U1-08", unit:1, topic:"1.4 Tides & currents", spec:"1.4/LO5", tier:1, type:"truefalse",
    stem:"A gyre is a large system of circular ocean currents.",
    answer:true,
    why:"A gyre is a large system of circular currents driven by winds and the Earth's rotation.",
    misconception:"a gyre is a whirlpool that pulls things under" },

  // ============================ UNIT 2 — Sea water ============================
  { id:"TF-U2-01", unit:2, topic:"2.1 Water cycle & states", spec:"2.1/LO6", tier:2, type:"truefalse",
    stem:"When floating sea ice melts, it raises the sea level.",
    answer:false,
    why:"Floating ice already displaces its own mass of water, so melting it does not change the level; it is land-based ice (glaciers, ice sheets) that raises sea level.",
    misconception:"all melting ice raises sea level" },
  { id:"TF-U2-02", unit:2, topic:"2.2 pH & salinity", spec:"2.2/LO9", tier:1, type:"truefalse",
    stem:"Heavy rainfall and river run-off lower the salinity of sea water.",
    answer:true,
    why:"Both add fresh water, diluting the dissolved salts, so salinity falls.",
    misconception:"rain makes the sea saltier 'because rain carries salt'" },
  { id:"TF-U2-03", unit:2, topic:"2.3 Dissolved gases", spec:"2.3/LO3", tier:2, type:"truefalse",
    stem:"Warm water can hold more dissolved oxygen than cold water.",
    answer:false,
    why:"Gas solubility decreases as temperature rises, so warm water holds less dissolved oxygen.",
    misconception:"the solids-solubility rule applied to gases" },
  { id:"TF-U2-04", unit:2, topic:"2.6 Upwelling", spec:"2.6/LO1", tier:1, type:"truefalse",
    stem:"Upwelling brings cold, nutrient-rich water up to the surface.",
    answer:true,
    why:"Wind moves surface water away and cold, nutrient-rich deep water rises to replace it, supporting high productivity.",
    misconception:"upwelling is warm water rising" },
  { id:"TF-U2-05", unit:2, topic:"2.4 Density", spec:"2.4/LO3", tier:1, type:"truefalse",
    stem:"Salty water is denser than fresh water.",
    answer:true,
    why:"Dissolved salt adds mass to the same volume, so saltier water is denser.",
    misconception:"salt makes water 'lighter'" },
  { id:"TF-U2-06", unit:2, topic:"2.2 pH & salinity", spec:"2.2/LO2", tier:1, type:"truefalse",
    stem:"Sea water is slightly alkaline.",
    answer:true,
    why:"Sea water is slightly alkaline (about pH 8); fresh water is roughly neutral and rain water is slightly acidic.",
    misconception:"sea water is acidic because it is salty" },
  { id:"TF-U2-07", unit:2, topic:"2.5 Depth", spec:"2.5/LO4", tier:1, type:"truefalse",
    stem:"Pressure decreases as you go deeper in the ocean.",
    answer:false,
    why:"Pressure increases with depth because the weight of the water above increases.",
    misconception:"pressure is highest at the surface" },
  { id:"TF-U2-08", unit:2, topic:"2.6 Upwelling", spec:"2.6/LO2", tier:2, type:"truefalse",
    stem:"During an El Niño year the Pacific trade winds strengthen.",
    answer:false,
    why:"In an El Niño the trade winds weaken or reverse, warm water shifts east, and eastern-Pacific upwelling is reduced.",
    misconception:"the trade winds strengthen in El Niño" },

  // ============================ UNIT 3 — Marine organisms ============================
  { id:"TF-U3-01", unit:3, topic:"3.1 Cells", spec:"3.1/LO1", tier:1, type:"truefalse",
    stem:"Plant cells have a cell wall instead of a cell membrane.",
    answer:false,
    why:"A plant cell has a cell wall outside its cell membrane — both are present; the wall does not replace the membrane.",
    misconception:"the wall replaces the membrane" },
  { id:"TF-U3-02", unit:3, topic:"3.3 Classification", spec:"3.3/LO2", tier:1, type:"truefalse",
    stem:"In a binomial name, the first part is the genus and the second is the species.",
    answer:true,
    why:"The two-part scientific name gives the genus first, then the species (e.g. Orcinus orca).",
    misconception:"species written first" },
  { id:"TF-U3-03", unit:3, topic:"3.3 Classification", spec:"3.3/LO3", tier:1, type:"truefalse",
    stem:"The three domains of life are Bacteria, Archaea and Eukarya.",
    answer:true,
    why:"These are the three domains; animals, plants and protoctists are kingdoms within Eukarya.",
    misconception:"'animals/plants/protoctists' given as domains" },
  { id:"TF-U3-04", unit:3, topic:"3.1 Cells", spec:"3.1/LO2", tier:1, type:"truefalse",
    stem:"Bacterial cells contain a nucleus.",
    answer:false,
    why:"Bacterial cells have a wall, membrane and cytoplasm but no nucleus; their genetic material lies in the cytoplasm.",
    misconception:"all cells have a nucleus" },
  { id:"TF-U3-05", unit:3, topic:"3.2 Reproduction", spec:"3.2/LO2", tier:1, type:"truefalse",
    stem:"In sexual reproduction the offspring are identical to one parent.",
    answer:false,
    why:"Male and female sex cells fuse, so the offspring have a mix of characteristics from both parents, not an identical copy of one.",
    misconception:"sexual offspring are clones of a parent" },
  { id:"TF-U3-06", unit:3, topic:"3.1 Cells", spec:"3.1/LO4", tier:1, type:"truefalse",
    stem:"Mitochondria are where photosynthesis takes place.",
    answer:false,
    why:"Mitochondria are where respiration releases energy; photosynthesis takes place in chloroplasts.",
    misconception:"mitochondria and chloroplasts confused" },
  { id:"TF-U3-07", unit:3, topic:"3.5 Plant & protoctist kingdoms", spec:"3.3/LO4", tier:1, type:"truefalse",
    stem:"Kelp belongs to the protoctist kingdom.",
    answer:true,
    why:"Kelp is a large protoctist (a seaweed), not a true plant.",
    misconception:"kelp is a plant" },
  { id:"TF-U3-08", unit:3, topic:"3.7 Migration", spec:"3.7", tier:2, type:"truefalse",
    stem:"Lanternfish move up towards the surface at night to feed and avoid predators.",
    answer:true,
    why:"They make a daily vertical migration: feeding near the surface in darkness where there is food, and avoiding predators that hunt by sight.",
    misconception:"they migrate up to breathe air" },

  // ============================ UNIT 4 — Nutrients and energy ============================
  { id:"TF-U4-01", unit:4, topic:"4.4 Feeding relationships", spec:"4.4/LO2", tier:1, type:"truefalse",
    stem:"In a food chain the arrows point from the predator to its prey.",
    answer:false,
    why:"Arrows point from the eaten organism to the eater, showing the direction of energy transfer.",
    misconception:"arrows mean 'eats' and point at the food" },
  { id:"TF-U4-02", unit:4, topic:"4.4 Feeding relationships", spec:"4.4/LO9", tier:2, type:"truefalse",
    stem:"A detritivore and a decomposer are the same thing.",
    answer:false,
    why:"A detritivore is an animal that eats dead or waste material; a decomposer (e.g. bacteria) gets its energy by breaking that material down.",
    misconception:"the two terms treated as identical" },
  { id:"TF-U4-03", unit:4, topic:"4.4 Feeding relationships", spec:"4.4/LO12", tier:1, type:"truefalse",
    stem:"Energy is lost along a food chain through respiration, movement and excretion.",
    answer:true,
    why:"These (with removal/harvesting) are the routes energy is lost, so only a fraction passes to the next level.",
    misconception:"energy is destroyed / the eater keeps it all" },
  { id:"TF-U4-04", unit:4, topic:"4.2 Respiration", spec:"4.2/LO2", tier:2, type:"truefalse",
    stem:"Only animals respire; producers such as seaweed do not.",
    answer:false,
    why:"All living cells respire, including producers; at night, with no photosynthesis, producers release carbon dioxide.",
    misconception:"plants only photosynthesise, they don't respire" },
  { id:"TF-U4-05", unit:4, topic:"4.4 Feeding relationships", spec:"4.4/LO1", tier:1, type:"truefalse",
    stem:"The Sun is the principal source of energy for marine food webs.",
    answer:true,
    why:"The Sun is the principal energy input; producers capture it in photosynthesis.",
    misconception:"producers or nutrients are 'the energy source'" },
  { id:"TF-U4-06", unit:4, topic:"4.3 Photosynthesis", spec:"4.3", tier:1, type:"truefalse",
    stem:"Photosynthesis releases oxygen.",
    answer:true,
    why:"Producers use light to make carbohydrates from carbon dioxide and water, releasing oxygen — a source of dissolved oxygen in the sunlight zone.",
    misconception:"photosynthesis uses up oxygen" },
  { id:"TF-U4-07", unit:4, topic:"4.4 Feeding relationships", spec:"4.4/LO7", tier:1, type:"truefalse",
    stem:"A primary consumer feeds on producers.",
    answer:true,
    why:"A primary consumer (trophic level 2) eats the producer; a secondary consumer eats the primary, and so on.",
    misconception:"level fixed by body size" },
  { id:"TF-U4-08", unit:4, topic:"4.4 Feeding relationships", spec:"4.4/LO13", tier:2, type:"truefalse",
    stem:"An energy pyramid can be wider at the top than at the bottom.",
    answer:false,
    why:"Because energy is lost at every level, an energy pyramid is always upright (narrowing upwards); only a pyramid of numbers or biomass can appear inverted.",
    misconception:"all pyramids can be any shape" },

  // ============================ UNIT 5 — Marine ecosystems ============================
  { id:"TF-U5-01", unit:5, topic:"5.5 Sedimentary shore", spec:"5.5/LO2", tier:2, type:"truefalse",
    stem:"A muddy shore contains more oxygen than a sandy shore.",
    answer:false,
    why:"Fine mud particles pack together and waterlog, holding little oxygen; a sandy shore has air spaces between its larger grains, so more oxygen.",
    misconception:"mud = more oxygen" },
  { id:"TF-U5-02", unit:5, topic:"5.7 Coral reef", spec:"5.7/LO4", tier:1, type:"truefalse",
    stem:"The relationship between coral polyps and their zooxanthellae is one in which both partners benefit.",
    answer:true,
    why:"It is mutualism: the polyp gains sugars and oxygen from the algae's photosynthesis; the algae gain shelter, carbon dioxide and nutrients.",
    misconception:"parasitism / the polyp eats the algae" },
  { id:"TF-U5-03", unit:5, topic:"5.6 Mangrove", spec:"5.6/LO3", tier:1, type:"truefalse",
    stem:"Mangrove aerial roots (pneumatophores) take in oxygen for respiration.",
    answer:true,
    why:"Waterlogged mud holds little oxygen, so pneumatophores exposed to the air take in oxygen for the roots to respire.",
    misconception:"aerial roots are only for support / absorb water vapour" },
  { id:"TF-U5-04", unit:5, topic:"5.7 Coral reef", spec:"5.7/LO5", tier:2, type:"truefalse",
    stem:"Coral bleaching happens when the water becomes too cold.",
    answer:false,
    why:"Bleaching occurs when the water is too warm, causing the polyps to expel their zooxanthellae and lose their colour.",
    misconception:"bleaching from cold / sunscreen / depth" },
  { id:"TF-U5-05", unit:5, topic:"5.3 Open ocean", spec:"5.3/LO3", tier:1, type:"truefalse",
    stem:"The sunlight zone reaches from the surface down to about 200 m.",
    answer:true,
    why:"Sunlight 0–200 m, twilight 200–1000 m, midnight below 1000 m.",
    misconception:"the zones set at the wrong depths" },
  { id:"TF-U5-06", unit:5, topic:"5.3 Open ocean", spec:"5.3/LO6", tier:1, type:"truefalse",
    stem:"Phytoplankton are consumers.",
    answer:false,
    why:"Phytoplankton (diatoms, dinoflagellates, cyanobacteria) are microscopic producers that photosynthesise.",
    misconception:"plankton are all animals" },
  { id:"TF-U5-07", unit:5, topic:"5.3 Open ocean", spec:"5.3/LO11", tier:2, type:"truefalse",
    stem:"The midnight zone has little dissolved oxygen because there is no photosynthesis there.",
    answer:true,
    why:"With no light there is no photosynthesis to add oxygen, and respiration/decomposition of sinking matter uses it up.",
    misconception:"pressure squeezes the oxygen out / cold water can't hold oxygen" },
  { id:"TF-U5-08", unit:5, topic:"5.3 Open ocean", spec:"5.3/LO4", tier:1, type:"truefalse",
    stem:"The sunlight zone is low in dissolved oxygen.",
    answer:false,
    why:"The sunlight zone is high in dissolved oxygen — it dissolves from the atmosphere and photosynthesis adds more.",
    misconception:"oxygen is scarce near the surface" },

  // ============================ UNIT 6 — Human influences ============================
  { id:"TF-U6-01", unit:6, topic:"6.7 Eutrophication", spec:"6.7/LO5", tier:2, type:"truefalse",
    stem:"During eutrophication the algal bloom lowers the oxygen straight away, because the algae use it up.",
    answer:false,
    why:"Living algae photosynthesise and release oxygen; the oxygen falls later, when the dead bloom is decomposed and the decomposers' respiration uses up the oxygen.",
    misconception:"'more algae = less oxygen immediately' (the O2 paradox)" },
  { id:"TF-U6-02", unit:6, topic:"6.8 Climate", spec:"6.8/LO6", tier:2, type:"truefalse",
    stem:"As the ocean warms, sea water holds less dissolved oxygen.",
    answer:true,
    why:"Gas solubility falls as temperature rises, so a warming ocean holds less dissolved oxygen and species may move or die.",
    misconception:"warm water holds more oxygen" },
  { id:"TF-U6-03", unit:6, topic:"6.6 Plastic", spec:"6.6/LO1", tier:1, type:"truefalse",
    stem:"Plastic in the sea is quickly broken down by bacteria within a few months.",
    answer:false,
    why:"Plastic persists for very long periods; sunlight and waves only fragment it into ever-smaller microplastics and release toxins — it does not rot.",
    misconception:"bacteria decompose plastic in months" },
  { id:"TF-U6-04", unit:6, topic:"6.9 Conservation", spec:"6.9/LO1", tier:1, type:"truefalse",
    stem:"Species richness is the number of different species in an area.",
    answer:true,
    why:"Richness counts the different species present — not the number of individuals and not biomass.",
    misconception:"richness = number of individuals" },
  { id:"TF-U6-05", unit:6, topic:"6.1 Overview", spec:"6.1/LO4", tier:1, type:"truefalse",
    stem:"A sustainable activity can continue without damaging the environment or making the resource run out.",
    answer:true,
    why:"Sustainable use means using a resource at the current rate, without damaging the environment and without it running out.",
    misconception:"renewable = sustainable at any rate" },
  { id:"TF-U6-06", unit:6, topic:"6.6 Plastic", spec:"6.6/LO3", tier:2, type:"truefalse",
    stem:"Floating plastic collects in the calm centre of a gyre, forming a garbage patch.",
    answer:true,
    why:"A gyre's circulating currents carry floating plastic towards the calm centre, where it accumulates as a garbage patch.",
    misconception:"garbage patches form on the seabed / from tidal currents" },
  { id:"TF-U6-07", unit:6, topic:"6.8 Climate", spec:"6.8/LO5", tier:2, type:"truefalse",
    stem:"Melting floating sea ice is a major cause of sea-level rise.",
    answer:false,
    why:"Floating sea ice already displaces its own weight of water; it is melting land-based ice (ice sheets and glaciers), plus thermal expansion of warming water, that raises sea level.",
    misconception:"the floating-ice result applied to land ice" },
  { id:"TF-U6-08", unit:6, topic:"6.9 Conservation", spec:"6.9/LO2", tier:2, type:"truefalse",
    stem:"In a marine protected area, fish species increase mainly because people feed the fish.",
    answer:false,
    why:"With fishing stopped the coral recovers, so its zooxanthellae photosynthesise, giving more energy, shelter and niches — which supports more fish species.",
    misconception:"fish increase because they are fed" },
];
